# Machine Learning and Data Mining: Graded Lab 01
---------------

#### Grading
For this graded lab you can get a total of **20 points**. These 20 points count **10%** of your final grade for the course.

#### Start
Start of the Graded Lab 01 is **Sunday, March 27th at 23:59**.

#### Deadline
Deadline for the submission of the Graded Lab 01 is **Sunday, April 10th at 23:59**.

#### Note
Check each result carefully. Use data cleaning and transformation methods wherever needed. The data can sometimes be really **messy**. Each cell should be **self-contained** and be able to be executed without **any** dependencies on previous cells.

#### Submission
You are allowed to submit the solution in groups of **two or three** students.
Submit your GradedLab01.ipynb file renamed to FirstnameStudent01LastnameStudent01_FirstnameStudent02LastnameStudent02_FirstnameStudent03LastnameStudent03.ipynb in moodle.   
Please submit a **runnable** python jupyter notebook file.
All other submissions will be rejected and graded with **0** points.

### Task 01: Implementation of content-based recommenders [total: 8 points].    
The movies.csv file contains a dataset extracted from IMDB with several attributes. For example, the title, plot, and the language of the movies. Read the movies.csv file in a pandas dataframe and try to answer the following questions.

##### __(a) The user Calvin hasn't watched any movies yet. Print the top 5 movies using the rating attribute as ranking, as recommendations for him [1 point].__

In [60]:
import pandas as pd
import seaborn as sns
import numpy as np

df = pd.read_csv('movies.csv')
df = df.sort_values('rating', ascending=False)
df.head()


## TODO: Remove duplicates, remove rows with incomplete values, etc.

,id,title,languages,genres,rating,director,plot
42,468569,The Dark Knight,"['English', 'Mandarin']","['Action', 'Crime', 'Drama', 'Thriller']",9.4,Christopher Nolan,Set within a year after the events of Batman B...
39,111161,The Shawshank Redemption,['english'],['Drama'],9.3,Frank Darabont,Chronicles the experiences of a formerly succe...
40,68646,The Godfather,"['English', 'Italian', 'Latin']","['Crime', 'Drama']",9.2,Francis Ford Coppola,"The Godfather ""Don"" Vito Corleone is the head ..."
41,71562,The Godfather: Part II,"['English', 'Italian', 'Spanish', 'Latin', 'Si...","['Crime', 'Drama']",9.0,Francis Ford Coppola,The continuing saga of the Corleone crime fami...
27,4138326,Fallout,['English'],"['Action', 'Adventure', 'Drama', 'Sci-Fi']",8.9,Stephen Surjik,"After the nuclear explosion, General Wade Eili..."

##### __(b) The user Calvin still hasn't watched any movies yet. We  just know that he likes english speaking movies. Print the top 5 movies using the rating attribute as ranking, which have only the english language in the languages attribute, as recommendations for him [1 point].__

In [61]:
import pandas as pd
import seaborn as sns
import numpy as np

df = pd.read_csv('movies.csv')
df = df.sort_values('rating', ascending=False)

df = df.loc[df['languages'].str.match("^\['[eE]nglish'\]")]
df.head()

# Note: We did not check if the languages are set correctly. There might be a result that in reallity has another language but it's not in the dataset.

,id,title,languages,genres,rating,director,plot
39,111161,The Shawshank Redemption,['english'],['Drama'],9.3,Frank Darabont,Chronicles the experiences of a formerly succe...
27,4138326,Fallout,['English'],"['Action', 'Adventure', 'Drama', 'Sci-Fi']",8.9,Stephen Surjik,"After the nuclear explosion, General Wade Eili..."
24,2912226,Unleash the Kraken!,['english'],"['Comedy', 'Crime', 'Fantasy']",8.7,Mike Smith,Just as the deadbeat father of the Johnson bro...
19,2187105,The Backward Class,['English'],"['Documentary', 'Drama']",8.6,Madeleine Grant,The first class of Dalit ('untouchable') caste...
14,502413,Frenzy,['English'],['Comedy'],8.4,Richard Boden,The new kitchen is now complete but Bill is to...

##### __(c) Still Calvin didn't watch a movie. However, we noticed that he took more time on the recommendations with the genres drama, thriller, crime, and comedy. Print the top 3 movies based on the rating attribute, which have at least the genres drama, thriller, crime, and comedy as recommendations for him [1 point].__

In [62]:
import pandas as pd
import seaborn as sns
import numpy as np

df = pd.read_csv('movies.csv')
df = df.sort_values('rating', ascending=False)

# In case the previous condition still applies.
# df = df.loc[df['languages'].str.match("^\['[eE]nglish'\]")]

df = df.loc[df['genres'].str.contains("[dD]rama|[tT]hriller|[cC]rime|[cC]omedy")]
df.head(3)

,id,title,languages,genres,rating,director,plot
42,468569,The Dark Knight,"['English', 'Mandarin']","['Action', 'Crime', 'Drama', 'Thriller']",9.4,Christopher Nolan,Set within a year after the events of Batman B...
39,111161,The Shawshank Redemption,['english'],['Drama'],9.3,Frank Darabont,Chronicles the experiences of a formerly succe...
40,68646,The Godfather,"['English', 'Italian', 'Latin']","['Crime', 'Drama']",9.2,Francis Ford Coppola,"The Godfather ""Don"" Vito Corleone is the head ..."

##### __(d) Now, Calvin has watched the movie with the ID 110912. Print the top 3 movies based on the rating attribute, which have the same director as the watched movie with the ID 110912 as recommendations for him. The already watched movie should not be within the recommendations [1 point].__

In [63]:
import pandas as pd
import seaborn as sns
import numpy as np

df = pd.read_csv('movies.csv')
df = df.sort_values('rating', ascending=False)

fav_director = df.loc[df['id'] == 110912]['director'].values[0]

df = df.loc[df['id'] != 110912]

df = df.loc[df['director'] == fav_director]
df.head(3)

# Note: Kill Bill Stellbox is a collection consisting of Vol 1 & 2 => The description is not accurate and the rating iis onlyt for one of them. 
#       We ignored this since it does not affect the results.

,id,title,languages,genres,rating,director,plot
33,105236,Reservoir Dogs,['English'],"['Drama', 'Thriller', 'Crime', 'Comedy']",8.3,Quentin Tarantino,"Six criminals, who are strangers to each other..."
0,1,Kill Bill Steelbox,['English'],"['Animation', 'Action', 'Adventure', 'Comedy',...",8.3,Quentin Tarantino,Placeholder for the Steelbox of Kill Bill.
37,361748,Inglourious Basterds,"['English', 'German', 'French', 'Italian']","['Adventure', 'Drama', 'War']",8.3,Quentin Tarantino,"In German-occupied France, young Jewish refuge..."

##### __(d) Now, Calvin has watched the movie with the ID 1502397 and we want to recommend movies with a similar plot. Remove all punctuation marks (".", ",", "(", ")", "-", "&"), convert the content to lower-case, and split the content of the plot attribute by whitespaces into terms. Then remove all stopwords by using the stopwords_english.txt file. Then calculate the Jaro Winkler distance (make use of an existing library) between the pre-processed plot of the watched movie and the pre-processed plots of all other movies. Print the top 3 movies based on the calculated  Jaro Winkler distance and the rating of the movie.  [4 points].__

In [64]:
import pandas as pd
import numpy as np
from strsimpy.jaro_winkler import JaroWinkler

df = pd.read_csv('movies.csv')
df = df.sort_values('rating', ascending=False)


def pp_plot(plot):
    punc = [".", ",", "(", ")", "-", "&"]
    for p in punc:
        plot = plot.replace(p, '')
    plot = plot.lower().split(' ')
    with open('stopwords_english.txt') as file:
        stop_words = file.readlines()
        stop_words = [s.replace("\n", "") for s in stop_words]
        
        # Idea 1 > Remove stop words by using a set => This removes duplicated words as well
        ### plot = set(plot) - set(stop_words)
        
        # Idea 2 > Remove stop words with a loop and keep duplicated words
        for i in range(len(plot)):
            if plot[i] in stop_words:
                plot[i] = ""
        
        plot = list(filter(None, plot))
    return plot

def get_diff(o_plot, n_plot):
    n_plot = pp_plot(n_plot)
    diff = np.array([])

    jarowinkler = JaroWinkler()
    
    # Idea 1 > Compare each word
    ### for p1 in o_plot:
    ###    for p2 in n_plot:
    ###        print(p1,p2)
    ###        res = jarowinkler.similarity(p1, p2)
    ###        diff = np.append(diff, res)
            
    
    # Idea 1.1 > Use the mean of all diffs
    ### return diff.mean()

    # Idea 1.2 > Use the mean of all diffs but first remove all 0 matches
    ### diff = diff[diff > 0]
    ### return diff.mean()

    # Idea 1.3 > Use the median
    ### return np.percentile(diff, 50)

    # Idea 1.4 > Use the sum
    ### return diff.sum()

    # Idea 2 > Compare word list
    return jarowinkler.similarity(list(o_plot), list(n_plot))
    

# Cleanup that is done after assesing the results
# Note: Only the necessary cleanup has been done. Obvious mistakes that do not affect the outcome are ignored.
original_plot = df.loc[df['id'] == 1502397]['plot'].values[0]
df = df.loc[df['plot'] != original_plot]
df = df.loc[df['id'] != 1502397]
df = df.loc[df['id'] != 9999999]

original_plot = pp_plot(original_plot)
# TODO: Is this a good approach?
for i, row in df.iterrows():
    df.at[i,'diff'] = get_diff(original_plot, row['plot'])

df = df.sort_values('diff', ascending=False) 
df.head(3)

,id,title,languages,genres,rating,director,plot,diff
44,380268,Cocaine Cowboys,['English'],"['Documentary', 'Crime', 'History']",7.8,Billy Corben,"In the 1980s, ruthless Colombian cocaine baron...",0.410714
10,967060,"Game, Set... Muuurder?",['English'],"['Comedy', 'Crime', 'Mystery']",7.7,James L. Conway,When a would be tennis star is reported missin...,0.383333
8,104927,Mr. Bond,['Hindi'],"['Action', 'Adventure', 'Thriller']",4.3,Raj N. Sippy,"Mr. Bond, a police officer by profession has a...",0.357639

### Task 02: Implementation of collaborative filtering recommenders [total: 12 points]. 
The ratings.csv file contains a dataset extracted from IMDB with ratings for movies in a range from 1 to 5 from several users. The meta-data for the movies is contained in the movies.csv file. Use the movies.csv file for printing the movie titles in the results. Implement a user-based and a item-based collaborative filtering recommendation engine like show in the lecture. Don't recommend any movies the user has already watched.

##### __(a)  Print the top 3 recommended movies for the users 'Delora', 'Ruth', 'Heather', 'Ronald', and 'Lakisha' in the dataset for the user-based version.  We use the threshold version for choosing similar users. The threshold for choosing the similar users needs to be set to 0.25. [5 points]__

In [65]:
import pandas as pd
import numpy as np
import operator

np.seterr(divide='ignore', invalid='ignore')

df_ratings = pd.read_csv('ratings.csv')
df_movies = pd.read_csv('movies.csv')

# Cleanup Data
df_movies = df_movies[df_movies.id != 9999999]
df_ratings = df_ratings.drop(df_ratings[df_ratings.rating < 1].index)
df_ratings = df_ratings.drop(df_ratings[df_ratings.rating > 5].index)

cos_sim = lambda a,b: np.dot(a,b.T)/(np.linalg.norm(a) * np.linalg.norm(b))

def sim(user, rating_matrix):   
    user_rating = rating_matrix[rating_matrix.index == user]
    other_user_rating = rating_matrix[rating_matrix.index != user]

    user_rating = user_rating.loc[:, (user_rating.isnull().sum(axis=0) <= 0)]
    other_user_rating = other_user_rating[user_rating.columns]
    
    similarities = pd.DataFrame(np.zeros((len(other_user_rating.index))), other_user_rating.index, columns=['similarity'])
    
    
    for idx, row in other_user_rating.iterrows():
        other_user = pd.DataFrame(row).transpose()
        other_user = other_user.loc[:, (other_user.isnull().sum(axis=0) <= 0)]
        
        common_cols = list(set(user_rating.columns).intersection(other_user.columns))
        
        if len(common_cols) == 0:
            similarities.at[row.name, 'similarity'] = 0
        else:
            sim = cos_sim(user_rating[common_cols], other_user[common_cols])
            similarities.at[row.name, 'similarity'] = sim[0][0]
    
    index_similarity = pd.DataFrame(similarities, other_user_rating.index, columns=['similarity'])
    index_similarity.index.name = 'user'
    index_similarity = index_similarity.sort_values('similarity', ascending=False)
    index_similarity = index_similarity.drop(index_similarity[index_similarity.similarity <= 0.25].index)
    
    return index_similarity

def recommend(user, similar_users, rating_matrix, k=3):
    
    # Get ratings from similar users
    similar_user_rating = rating_matrix.loc[similar_users.index]
    
    # Load current user ratings
    current_user_rating = rating_matrix.loc[[user]].transpose()
    current_user_rating.columns = ['rating']
    current_user_rating = current_user_rating.dropna()
    
    all_movie_indices = similar_user_rating.columns
    watched_movies = current_user_rating.index.values.tolist()
    
    # Get movies that are not watched by the user 
    unwatched_moves = list(set(all_movie_indices) - set(watched_movies))
    
    recommendations = pd.DataFrame(columns=['movie','recommendation'])
    for idx, movie in enumerate(unwatched_moves):
        ratings_by_users = similar_user_rating[movie].dropna()
        
        val_0 = 0
        for user, rating in ratings_by_users.iteritems():
            sim = similar_users.loc[user][0]
            val_0 += sim * rating
        
        val_1 = 1
        for user, rating in ratings_by_users.iteritems():
            sim = similar_users.loc[user][0]
            val_1 += sim
            
        rec = pd.DataFrame([[movie,(val_0 / val_1)]], columns=['movie','recommendation'])
        recommendations = pd.concat([recommendations, rec])
    
    recommendations = recommendations.sort_values('recommendation', ascending=False)
    return recommendations[:k]


rating_matrix = df_ratings.pivot_table(index='user', columns='id', values='rating')
sim_matrix = pd.DataFrame(index=rating_matrix.index)

for user in sim_matrix.index:
    print('.', end = '' )
    sim_matrix[user] = sim(user, rating_matrix)

names = ['Delora', 'Ruth', 'Heather', 'Ronald', 'Lakisha']
for name in names:
    print('\n', name)
    reccomendations = recommend(name, sim(name, rating_matrix), rating_matrix)
    for idx, row in reccomendations.iterrows():
        movie = df_movies.loc[df_movies['id'] == row['movie']]['title'].values[0]
        print('  -', movie, row['movie'])
        print('   ', row['recommendation'])

.............................................................................................
 Delora
  - The Godfather 68646
    3.1861939820147485
  - Inglourious Basterds 361748
    3.186096057142155
  - The Hateful Eight 3460252
    3.0499527089920986

 Ruth
  - The Godfather 68646
    3.2131594993632406
  - The Shawshank Redemption 111161
    2.9171386522778504
  - The Godfather: Part II 71562
    2.628123113168344

 Heather
  - The Godfather 68646
    3.170627127283338
  - The Godfather: Part II 71562
    2.72005028740941
  - Bad Boys for Life 1502397
    2.72005028740941

 Ronald
  - The Godfather 68646
    3.1583738612567087
  - The Hateful Eight 3460252
    3.0488587523578077
  - The Godfather: Part II 71562
    2.7346494650635935

 Lakisha
  - The Godfather 68646
    3.119840488257251
  - The Hateful Eight 3460252
    3.0489219274684554
  - Reservoir Dogs 105236
    3.008859877808306

##### __(b)  Print the user, which has the movie 'Calle 54' as best recommendation for the user-based version from Task 02 a)? [1 point]__

In [66]:
# Depends on cell 2a to be executed first!

names = df_ratings['user'].unique()
for name in names:
    reccomendations = recommend(name, sim(name, rating_matrix), rating_matrix, 15)
    for idx, row in reccomendations.iterrows():
        movie = df_movies.loc[df_movies['id'] == row['movie']]['title'].values[0]
        if movie == 'Calle 54':
            print('-', name)

- Paloma
- Beat

##### __(c)  Print the top 3 recommended movies for the users 'Harold', 'Alfredo', 'Jerry', 'Monica', and 'Gail' in the dataset for the item-based version.  We also use the threshold version for choosing similar items. The threshold for choosing the similar items needs to be set to 0.35. [4 points]__

In [58]:
import pandas as pd
import seaborn as sns
import numpy as np

df_r = pd.read_csv('ratings.csv')
df_m = pd.read_csv('movies.csv')

# Cleanup Data
df_movies = df_movies[df_movies.id != 9999999]
df_ratings = df_ratings.drop(df_ratings[df_ratings.rating < 1].index)
df_ratings = df_ratings.drop(df_ratings[df_ratings.rating > 5].index)

def similarity(item_v1, item_v2):
    dividend = sum(item_v1 * item_v2)
    divisor = np.linalg.norm(item_v1, 2) * np.linalg.norm(item_v2, 2)
    return dividend / divisor

def recommendationItemBased(user, n):
    recommendation_items = pd.DataFrame(columns=['id','recommendation','title'])

    #all rated items from user
    items_user_rating = df_r.loc[df_r['user'] == user]
    
    items_probably_not_rated = pd.DataFrame(columns=['id_rate', 'rate', 'id_sim', 'similarity'])
    
    for index, row in items_user_rating.iterrows():     
        item = row['id']
        rating = row['rating']
        similarity_row_items = similarity_item.loc[similarity_item['id_1'] == item]

        for i, sim_item in similarity_row_items.iterrows():           
            item = pd.DataFrame([[item, rating, sim_item['id_2'], sim_item['similarity']]], 
                                 columns=['id_rate', 'rate', 'id_sim', 'similarity'])
            items_probably_not_rated = pd.concat([items_probably_not_rated, item])
         
    #select only unrated items from user
    items_not_rated = items_probably_not_rated.loc[~items_probably_not_rated.id_sim.isin(items_user_rating.id)]
    
    #print(items_not_rated)
    
    #calculate recommendation for user not rated items
    for item in set(items_not_rated.id_sim):
        dividend = 0
        divisor = 0
        calc_recommendation = items_not_rated.loc[items_not_rated['id_sim'] == item]
        
        #calc for one item recommendation
        for in_calc, row_calc in calc_recommendation.iterrows():
            dividend += (row_calc['rate'] * row_calc['similarity'])
            divisor += row_calc['similarity']
        
        recommendation = dividend/divisor   
        rec_item = pd.DataFrame([[item, recommendation, df_m.loc[df_m['id'] == item]['title'].values[0]]],
                                columns=['id','recommendation','title'])
        recommendation_items = pd.concat([recommendation_items, rec_item])
    
    recommendation_items = recommendation_items.sort_values('recommendation', ascending=False)
    return recommendation_items[:n]

#create similarity matrix
similarity_item = pd.DataFrame(columns=['id_1','id_2','similarity'])
#create rating matrix
movie_matrix_user = df_r.pivot_table(index='user', columns='id', values='rating')
# replace NaN
movie_matrix_user = movie_matrix_user.fillna(0)


for in_row, row in enumerate(movie_matrix_user):
    print('.', end = '' )
    
    base_column = movie_matrix_user.iloc[:, in_row]
    base_column_id = movie_matrix_user.columns[in_row]
   
    for in_col, column in enumerate(movie_matrix_user):
   
        column_curr = movie_matrix_user[column]
        item = pd.DataFrame([[base_column_id, movie_matrix_user.columns[in_col],
                             similarity(column_curr,base_column)]], columns=['id_1','id_2','similarity']) 
        similarity_item = pd.concat([similarity_item, item])

#threshold 0.35 
similarity_item = similarity_item[similarity_item['similarity'] > 0.35]

names = ['Harold', 'Alfredo', 'Jerry', 'Monica', 'Gail']
for name in names:
    print('\n----------------------------------------------------')
    print('Recommendations for', name)
    print(recommendationItemBased(name, 3))

........................................
----------------------------------------------------
Recommendations for Harold
       id recommendation                     title
0  111161       3.261508  The Shawshank Redemption
0  119396       3.235485              Jackie Brown
0   68646            3.0             The Godfather

----------------------------------------------------
Recommendations for Alfredo
        id recommendation                 title
0  3460252       2.703756     The Hateful Eight
0   361748       2.656347  Inglourious Basterds
0   119396       2.029188          Jackie Brown

----------------------------------------------------
Recommendations for Jerry
       id recommendation                     title
0  111161       3.980503  The Shawshank Redemption
0  119396       3.367724              Jackie Brown
0  116367        3.06393       From Dusk Till Dawn

----------------------------------------------------
Recommendations for Monica
        id recommendation                   title
0    71562            3.0  The Godfather: Part II
0  1502397            3.0       Bad Boys for Life
0    68646       1.405684           The Godfather

----------------------------------------------------
Recommendations for Gail
        id recommendation              title
0   119396       3.885825       Jackie Brown
0  3460252         3.3448  The Hateful Eight
0   105236       3.301122     Reservoir Dogs

##### __(d) Print the user, which has the movie 'Pomerania Courier' as best recommendation for the item-based version from Task 02 c)? [1 point]__

In [34]:
# Depends on cell 2c to be executed first!

import pandas as pd
import seaborn as sns
import numpy as np

df_r = pd.read_csv('ratings.csv')
df_m = pd.read_csv('movies.csv')

id_movie = df_m.loc[df_m['title'] == 'Pomerania Courier']['id'].values[0]

names = df_r['user'].unique()
users_rec = pd.DataFrame(columns=['user', 'recommendation', 'title'])

for name in names:
    print('.', end = '' )
    reccomendations = recommendationItemBased(name, 30)
    for idx, row in reccomendations.iterrows():    
        if row['id'] == id_movie:
            rec =  pd.DataFrame([[ name, row['recommendation'], row['title']]],columns=['user', 'recommendation', 'title'])
            users_rec = pd.concat([users_rec, rec])
            

users_rec = users_rec.sort_values('recommendation', ascending=False)
users_rec.head()
#there are two people (Chantal and Paloma) with the identical recommendation

.............................................................................................

      user recommendation              title
0  Chantal            5.0  Pomerania Courier
0   Paloma            5.0  Pomerania Courier
0     Beat            1.0  Pomerania Courier

##### __(e) Which movies are the most recommended ones? Print the top3 movies generated with the recommender from Task 02 a). [1 point]__

In [31]:
# Depends on cell 2a to be executed first!

names = df_ratings['user'].unique()
move_rec = pd.DataFrame(columns=['id', 'recommendation', 'title'])
for name in names:
    print('.', end = '' )
    reccomendations = recommend(name, sim(name, rating_matrix), rating_matrix, 15)
    for idx, row in reccomendations.iterrows():
        movie = df_movies.loc[df_movies['id'] == row['movie']]['title'].values[0]
        rec =  pd.DataFrame([[ row['movie'], row['recommendation'], movie]],columns=['id', 'recommendation', 'title'])
        move_rec = pd.concat([move_rec, rec])
        
move_rec = move_rec.set_index(['id'])
move_rec = move_rec.sort_values('recommendation', ascending=False)  
move_rec = move_rec.drop_duplicates(subset=['title'])
move_rec.head(3)

.............................................................................................

/opt/homebrew/lib/python3.9/site-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)

        recommendation          title
id
4138326       3.310574        Fallout
68646         3.294983  The Godfather
2130022       3.269223    Enchantress